### PR TITLE
add mason

### PR DESCRIPTION
**Pull request by fumieval**
Added [mason](https://hackage.haskell.org/package/mason) to the benchmark subjects

### CODE REVIEW

**Comment by andrewthad** [comment]
Looks good. Thanks!

**Comment by andrewthad** [comment]
Wait. There's something weird going on. This PR doesn't actually the `Encode.Mason` module. Is this an oversight?

**Comment by fumieval** [comment]
> Wait. There's something weird going on. This PR doesn't actually the Encode.Mason module. Is this an oversight?

Yeah sorry, that's a classic oversight! Fixed.

**Comment by andrewthad** [comment]
Awesome. Thanks!

**Pull request merged**
